authentication_app/urls.py
from django.urls import path

from .views import auth_login,auth_register,auth_logout,auth_reset_password

app_name = "Authentication"

urlpatterns = [
    path('login',auth_login,name='login'),
    path('register',auth_register,name='register'),
    path('logout',auth_logout,name='logout'),
    path("reset-password",auth_reset_password,name="reset_password")
]

chat_app/urls.py
from django.urls import path

from .views import home,dashboard,tasks



from .chat_views.chat_view import ChatView,chats_home
from .chat_views.notifications_view import NotificationsView
from .chat_views.friends_view import FriendsView
from .chat_views.settings_view import SettingsView
from .chat_views.search_view import SearchView

app_name = "Chatapp"

urlpatterns = [
    path('',home,name='home'),
    path('dashboard',dashboard,name='dashboard'),
    path('tasks',tasks,name="tasks"),

    path('chats',chats_home,name="chats_home"),
    path('chats/<str:username>',ChatView.as_view(),name="chats"),

    path('notifications',NotificationsView.as_view(),name="notifications"),
    path('friends',FriendsView.as_view(),name="friends"),
    path("search",SearchView.as_view(),name="search"),
    path("settings",SettingsView.as_view(),name="settings")

]

languagelab/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authentication_app.urls')),
    path('',include('chat_app.urls'))
]

authentication_app/models.py
from django.db import models

# Create your models here.

chat_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from languagelab import settings
from .custom_exceptions import FriendRequestFailedException

# Create your models here.
class UserAccount(AbstractUser):
    profile_pic = models.ImageField(upload_to = "static/profiles")
    location = models.CharField(max_length=50,default="Somewhere")
    description = models.TextField()
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True)

    def _str__(self):
        return f"<UserAccount @{self.username}"

    


    

class FriendRequest(models.Model):
    """ Model to represent a FriendRequest """
    from_user = models.ForeignKey(UserAccount,on_delete=models.CASCADE,related_name="friend_request_from_user")
    to_user = models.ForeignKey(UserAccount,on_delete=models.CASCADE,related_name="friend_request_to_user")

    @classmethod
    def send_friend_request(cls,from_user:UserAccount,to_username):
        """ Sends a friend request to a valid user object else raises an exception """
        # Check if username has an account
        to_user_account = UserAccount.objects.filter(username=to_username).first()
        if not to_user_account:
            raise FriendRequestFailedException(f"Failed while sending request. Username {to_username} is unregistered")
        
        # If username is valid, so account is valid the we proceed to send friend request
        new_friend_request = FriendRequest(from_user=from_user,to_user=to_user_account)
        new_friend_request.save()

        from_user.friend_request_to_user.add(new_friend_request)
        return new_friend_request



class Language(models.Model):
    name = models.CharField(max_length=20)
    fluency = models.CharField(max_length=20,choices=(
        ("BEGINNER","beginner"),
        ("INTERMEDIATE","intermediate"),
        ("FLUENT","fluent"),
        ("NATIVE","native")
    ),default="BEGINNER")

    user = models.ForeignKey(UserAccount,on_delete=models.CASCADE)

# class Friend(models.Model):
#     users = models.ManyToManyField(UserAccount)
#     current_user = models.ForeignKey(UserAccount,related_name="owner",null=True,on_delete=models.CASCADE)

#     @classmethod
#     def make_friend(cls,current_user,new_friend):
#         friend,created = cls.objects.get_or_create(
#             current_user = current_user
#         )

authentication_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.hashers import make_password,check_password
from django.contrib import messages

from chat_app.models import  UserAccount,Language

# Create your views here.
def auth_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = UserAccount.objects.filter(username=username).first()
        if user:
            if check_password(password,user.password):
                login(request,user)
                messages.success(request,f"Successfully logged in as {user.username}")
                return redirect("Chatapp:dashboard")
            else:
                messages.error(request,"Incorrect Password")
        else:
            messages.error(request,"Sorry,the account was not found")

    return render(request,"signin.html")

def auth_register(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        remember = request.POST.get("remember")

        user = UserAccount.objects.filter(username=username).first()

        if user:
            messages.error(request,"Username is not available")
        else:
            user = UserAccount(username=username,email=email,password=make_password(password))
            user.save()
            login(request,user)
            messages.success(request,f"Successfully logged in as {user.username}")
            return HttpResponseRedirect("dashboard")
            
    return render(request,"signup.html")

def auth_logout(request):
    logout(request)
    messages.success(request,"Successfully logged out")

    return HttpResponseRedirect("/")

def auth_reset_password(request):
    return HttpResponse("resetting password")

chat_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.views import View

from .models import UserAccount

# Create your views here.
def home(request):
    context = {
    }
    return render(request,"landing_page.html",context=context)

@login_required(login_url="Authentication:login")
def dashboard(request):
    context = {
        "counts":range(20)
    }
    return render(request,"index.html",context=context)


@login_required(login_url="Authentication:login")
def tasks(request):
    context = {
        "counts":range(20)
    }
    return render(request,"tasks.html",context=context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" style="overflow:hidden;">

<head>
    <meta charset="utf-8">
    <title>LexiKon</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet"> 
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
</head>

<body style="overflow:hidden;">
    {% if messages %}
        <div id="messages" >
            {% for message in messages %}
                <div class ="message {{ message.level_tag }}">
                    <i class="fa fa-exclamation-circle me-2"></i>{{ message }}
                    <button class="close-btn" onclick="dismissAlert()">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3 glass">
            <nav class="navbar">
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{user.username}}</h6>
                    </div>
                </div>
                <div class="navbar-nav w-100 gap-2">
                    <a href="/search" class="nav-item nav-link"><i class="fa fa-search me-2"></i>Search</a>
                    <a href="/chats" class="nav-item nav-link"><i class="fa fa-comments me-2"></i>Chats</a>
                    <a href="/friends" class="nav-item nav-link"><i class="fa fa-users me-2"></i>Friends</a>
                    <a href="/notifications" class="nav-item nav-link"><i class="fa fa-bell me-2"></i>Notifications</a>
                    <a href="/settings" class="nav-item nav-link"><i class="fa fa-cog me-2 fa-spin"></i>Settings</a>
                    
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->

        
        <!-- Back to Top -->
        {% comment %} <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a> {% endcomment %}
    </div>
    
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand elevated glass navbar-dark sticky-top px-4 py-0" style="height:77px;">
        <a href="#" class="sidebar-toggler flex-shrink-0">
            <i class="fa fa-bars fa-2x"></i>
        </a>

        <div id="navbar-heading">
            <h1 class="mb-0">{{navbar_text}}</h1>
            <input type="text" id="general-searchbar" placeholder="Search Friends">
        </div>
        
        <div class="navbar-nav align-items-center ms-auto">
            <div class="d-flex align-items-center">
                <div class="position-relative">
                    <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                    <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                </div>
            </div>
            
        </div>
    </nav>
    <!-- Navbar End -->
    {% block body %}
    {% endblock %}
    
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

templates/base_auth.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Language Lab</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/lab-logo.png' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet"> 
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

    
</head>

<body style="overflow-x:hidden;">
    {% if messages %}
        <div id="messages" >
            {% for message in messages %}
                <div class ="message {{ message.level_tag }}">
                    <i class="fa fa-exclamation-circle me-2"></i>{{ message }}
                    <button class="close-btn" onclick="dismissAlert()">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
    </div>

    

    {% block auth_dynamic_content %}
    {% endblock %}
    
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

templates/chats.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <!-- Content Start -->
    <div class="content" style="">
        <!-- Widgets Start -->
        <div class="container-fluid pt-2 px-1">
            <div class="chatbanner">
                <div id="current-chat">
                    <div id="chatdetails">
                        <span id="chat-username">{{friend_info.username}}</span>
                        <span id="chat-location">{{friend_info.location}}</span>
                    </div>
                    <div class="position-relative">
                        <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                </div>
            </div>
            <div class="chatcontainer">
                <div id="friends-profiles" class="">
                    {% for friend in friends %}
                        {% if friend.username != user.username %}
                            <div class="profilepic" data-username="{{friend.username}}" onclick="connectClient('{{friend.username}}')">
                                <img class="rounded-circle availability" src="/{{friend.profile_pic}}" alt="" style="width: 100%; min-width:40px;">
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                
                <div id="chats">
                    
                </div>

            </div>
            <div id="message-container">
                <textarea id="message" value="" placeholder="Type message ..."></textarea>
                <button id="send-btn" class="btn">
                    <i class="fa fa-paper-plane fa-lg"></i>
                </button>
                <button id="record-btn" class="btn">
                    <i class="fa fa-microphone fa-lg"></i>
                </button>
            </div>
        </div>
        <!-- Widgets End -->
    </div>
    <!-- Content End -->
{% endblock %}

templates/friends.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <!-- Content Start -->
    <div class="content" style="">
        <!-- Widgets Start -->
        <div class="friends-list">
            {% for friend in friends %}
                <div class="friend-list-item">
                    <div class="row1">
                        <div class="profilepic" data-username="{{friend.username}}" style="">
                            <img class="rounded-circle availability" src="/{{friend.profile_pic}}" alt="">
                        </div>
                        <div class="lower">
                            <span class="mb-0 text-bold">{{friend.username}}</span>
                            <span>{{friend.description}}</span>
                        </div>
                    </div>
                    <div class="action-buttons">
                        <button class="btn" style="color:var(--bs-red);"><i class="fa fa-trash fa-lg"></i></button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Content End -->
{% endblock %}

templates/home.html
{% extends 'basae.html' %}

{% block body %}

{% endblock %}

templates/signin.html
{% extends "base_auth.html" %}
{% load static %}
{% block auth_dynamic_content %}
    <!-- Sign In Start -->
    <div class="container-fluid" style="padding-right:0;padding-left:0;">
        <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
            <div class="col-sm-8 col-md-6 col-lg-5 col-xl-4">
                <div class="rounded p-4 p-sm-5 my-4 mx-3 card">
                    <div class="d-flex align-items-center justify-content-center gap-2 mb-3">
                        <a href="{% url 'Chatapp:home' %}" class="">
                            <h3 class="text-primary">
                                <div class="col-2" style="max-width:max-content;">
                                    <img src="{% static 'img/lab-logo.png' %}" alt="logos" height="60px" width="60px" class="img-normal">
                                </div>
                            </h3>
                        </a>
                        <h3>Login</h3>
                    </div>
                    <form action="{% url 'Authentication:login' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="floatingInput" autocomplete="off" name="username" placeholder=" ">
                            <label for="floatingInput">Username</label>
                        </div>
                        <div class="form-floating mb-4">
                            <input type="password" class="form-control" id="floatingPassword" autocomplete="off" name="password" placeholder=" ">
                            <label for="floatingPassword">Password</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <a href="{% url 'Authentication:reset_password' %}">Forgot Password</a>
                        </div>
                        <button type="submit" class="btn font-weight-bold atlas-cta atlas-cta-wide cta-green my-3">Login</button>
                    </form>
                    <p class="text-center mb-0 ">Don't have an Account? <a href="{% url 'Authentication:register' %}">Register</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Sign In End -->
{% endblock auth_dynamic_content %}

templates/signup.html
{% extends "base_auth.html" %}
{% load static %}

{% block auth_dynamic_content %}
    <!-- Sign Up Start -->
    <div class="container-fluid">
        <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
            <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
                <div class="rounded p-4 p-sm-5 my-4 mx-3 card">
                    <div class="d-flex align-items-center justify-content-center gap-2 mb-3">
                        <a href="{% url 'Chatapp:home' %}" class="">
                            <h3 class="text-primary">
                                <div class="col-2" style="max-width:max-content;">
                                    <img src="{% static 'img/lab-logo.png' %}" alt="logo" height="60px" width="60px" class="img-normal">
                                </div>
                            </h3>
                        </a>
                        <h3>Register</h3>
                    </div>
                    <form method='POST' action="{% url 'Authentication:register' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="username" autocomplete="off" placeholder=" ">
                            <label for="floatingText">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" name="email" autocomplete="off" placeholder=" ">
                            <label for="floatingInput">Email address</label>
                        </div>
                        <div class="form-floating mb-4">
                            <input type="password" class="form-control" name="password" autocomplete="off" placeholder=" ">
                            <label for="floatingPassword">Password</label>
                        </div>
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="remember" autocomplete="off" placeholder=" ">
                                <label class="form-check-label" for="exampleCheck1">Remember login</label>
                            </div>
                        </div>
                        <button type="submit" class="btn font-weight-bold atlas-cta atlas-cta-wide cta-green my-3">Register</button>
                    </form>
                    <p class="text-center mb-0">Already have an Account? <a href="{% url 'Authentication:login' %}">Login</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Sign Up End -->
{% endblock %}